#FROM redis:6.2-rc3-alpine3.13
FROM redis:latest
LABEL org.opencontainers.image.authors="nospam.joe@gmail.com"
LABEL org.opencontainers.image.source="https://github.com/jtb75/redis-sample"
LABEL org.opencontainers.image.vendor="jtb75-demo"
