name: Redis Sample Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_SECRET }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          echo "TAG=`date +%Y.%m.%d.%H.%M.%S`" >> $GITHUB_ENV
          echo "NODE_TLS_REJECT_UNAUTHORIZED=0" >> $GITHUB_ENV
      - name: Build the Docker image
        working-directory: ./container
        run: |
          docker build . --file Dockerfile --tag jtb75/redis-sample:$TAG --tag jtb75/redis-sample:latest
      - name: Prisma Cloud image scan
        id: scan
        uses: PaloAltoNetworks/prisma-cloud-scan@v1
        with:
          pcc_console_url: ${{ secrets.PCC_CONSOLE_URL }}
          pcc_user: ${{ secrets.PCC_USER }}
          pcc_pass: ${{ secrets.PCC_SECRET }}
          image_name: jtb75/redis-sample
      - name: Push the Docker image
        run: |
          docker push jtb75/redis-sample:$TAG
          docker push jtb75/redis-sample:latest
